export const MOCK_CATEGORIES = [
  { id: "salads", name: "Салаты" },
  { id: "cold-apps", name: "Холодные закуски" },
  { id: "hot-apps", name: "Горячие закуски" },
  { id: "soups", name: "Супы" },
  { id: "main", name: "Горячие блюда" },
  { id: "eastern", name: "Восточные блюда" },
]

export const MOCK_ITEMS = [
  // Салаты
  {
    id: "salad-1",
    name: "Салат Муравейник",
    description: "По умолчанию",
    price: 2890,
    image: "/placeholder.svg",
    category: "salads",
    tag: "default",
  },
  {
    id: "salad-2",
    name: "Ачи-чучук",
    description: "Хит продаж",
    price: 1000,
    image: "/placeholder.svg",
    category: "salads",
    tag: "bestseller",
  },
  {
    id: "salad-3",
    name: "Салат «Греческий»",
    description: "Свежие овощи с сыром фета и оливками",
    price: 2490,
    image: "/placeholder.svg",
    category: "salads",
    tag: "bestseller",
  },
  {
    id: "salad-4",
    name: "Цезарь с курицей",
    description: "Классический салат с куриным филе",
    price: 2690,
    image: "/placeholder.svg",
    category: "salads",
  },
  {
    id: "salad-5",
    name: "Оливье",
    description: "Традиционный салат с говядиной",
    price: 1990,
    image: "/placeholder.svg",
    category: "salads",
  },

  // Холодные закуски
  {
    id: "cold-1",
    name: "Сырная тарелка",
    description: "Ассорти из 4 видов сыра",
    price: 3490,
    image: "/placeholder.svg",
    category: "cold-apps",
    tag: "bestseller",
  },
  {
    id: "cold-2",
    name: "Мясное ассорти",
    description: "Нарезка из разных видов мяса",
    price: 4200,
    image: "/placeholder.svg",
    category: "cold-apps",
  },
  {
    id: "cold-3",
    name: "Рыбное ассорти",
    description: "Слабосоленая рыба и морепродукты",
    price: 3900,
    image: "/placeholder.svg",
    category: "cold-apps",
  },
  {
    id: "cold-4",
    name: "Овощное ассорти",
    description: "Свежие сезонные овощи",
    price: 1900,
    image: "/placeholder.svg",
    category: "cold-apps",
  },
  {
    id: "cold-5",
    name: "Соленья",
    description: "Домашние соленья и маринады",
    price: 1500,
    image: "/placeholder.svg",
    category: "cold-apps",
  },

  // Горячие закуски
  {
    id: "hot-1",
    name: "Креветки в кляре",
    description: "Тигровые креветки в хрустящем кляре",
    price: 3200,
    image: "/placeholder.svg",
    category: "hot-apps",
    tag: "bestseller",
  },
  {
    id: "hot-2",
    name: "Жульен грибной",
    description: "Запеченные грибы в сливочном соусе",
    price: 1800,
    image: "/placeholder.svg",
    category: "hot-apps",
  },
  {
    id: "hot-3",
    name: "Крылышки BBQ",
    description: "Куриные крылышки в соусе барбекю",
    price: 2200,
    image: "/placeholder.svg",
    category: "hot-apps",
  },
  {
    id: "hot-4",
    name: "Сырные шарики",
    description: "Жареные шарики из сыра",
    price: 1600,
    image: "/placeholder.svg",
    category: "hot-apps",
  },
  {
    id: "hot-5",
    name: "Кольца кальмара",
    description: "Кольца кальмара в панировке",
    price: 1900,
    image: "/placeholder.svg",
    category: "hot-apps",
  },

  // Супы
  {
    id: "soup-1",
    name: "Борщ",
    description: "Традиционный борщ со сметаной",
    price: 1500,
    image: "/placeholder.svg",
    category: "soups",
    tag: "bestseller",
  },
  {
    id: "soup-2",
    name: "Грибной крем-суп",
    description: "Нежный суп-пюре из белых грибов",
    price: 1800,
    image: "/placeholder.svg",
    category: "soups",
  },
  {
    id: "soup-3",
    name: "Том Ям",
    description: "Острый тайский суп с морепродуктами",
    price: 2500,
    image: "/placeholder.svg",
    category: "soups",
  },
  {
    id: "soup-4",
    name: "Куриный суп",
    description: "Домашний суп с лапшой",
    price: 1200,
    image: "/placeholder.svg",
    category: "soups",
  },
  {
    id: "soup-5",
    name: "Уха",
    description: "Рыбный суп из трех видов рыбы",
    price: 2200,
    image: "/placeholder.svg",
    category: "soups",
  },

  // Горячие блюда
  {
    id: "main-1",
    name: "Стейк Рибай",
    description: "Премиальный стейк из мраморной говядины",
    price: 7500,
    image: "/placeholder.svg",
    category: "main",
    tag: "bestseller",
  },
  {
    id: "main-2",
    name: "Лосось на гриле",
    description: "Филе лосося с овощами",
    price: 4900,
    image: "/placeholder.svg",
    category: "main",
  },
  {
    id: "main-3",
    name: "Паста Карбонара",
    description: "Классическая итальянская паста",
    price: 2800,
    image: "/placeholder.svg",
    category: "main",
  },
  {
    id: "main-4",
    name: "Куриное филе",
    description: "Сочное куриное филе с грибным соусом",
    price: 2500,
    image: "/placeholder.svg",
    category: "main",
  },
  {
    id: "main-5",
    name: "Утиная грудка",
    description: "Утиная грудка с апельсиновым соусом",
    price: 3900,
    image: "/placeholder.svg",
    category: "main",
  },

  // Восточные блюда
  {
    id: "eastern-1",
    name: "Плов",
    description: "Традиционный узбекский плов",
    price: 2800,
    image: "/placeholder.svg",
    category: "eastern",
    tag: "bestseller",
  },
  {
    id: "eastern-2",
    name: "Манты",
    description: "Сочные манты с мясом",
    price: 2200,
    image: "/placeholder.svg",
    category: "eastern",
  },
  {
    id: "eastern-3",
    name: "Лагман",
    description: "Восточный суп с домашней лапшой",
    price: 2400,
    image: "/placeholder.svg",
    category: "eastern",
  },
  {
    id: "eastern-4",
    name: "Шашлык",
    description: "Ассорти из разных видов шашлыка",
    price: 4500,
    image: "/placeholder.svg",
    category: "eastern",
  },
  {
    id: "eastern-5",
    name: "Самса",
    description: "Слоеные пирожки с мясом",
    price: 1800,
    image: "/placeholder.svg",
    category: "eastern",
  },
]

